### ISSUE TITLE
Origin of "update_changelog.py" tool?

### ISSUE THREAD

**Issue by isbm** [Elektrobit/flake-pilot#125]
@schaefi the `helper/update_changelog.py` seems copied from here:
https://github.com/OSInside/kiwi/commits/master/helper/update_changelog.py however, History of that file also doesn't looks original from the project and so it is not clear if the updater is GPL v3 or not. 😉 Nevertheless, since it comes from Kiwi which is under different license, this tool's licence needs to be properly mentioned.

Could you please fix that?

Alternatively, since it is a tool on its own, you could change its licence to permissive and allow more freedom (i.e. MIT or BSD), so it would be useful to bigger audience (as you wish).

**Comment by schaefi** [comment]
update_changelog.py is a simple python helper that I copy around in several projects. As it stays as helper in the code to create a changelog it can be imho re-licensed any time according to the project it's used in. Since I'm the exclusive copyright holder of it I will just make it MIT for the flake-pilot project

Expect a PR soon
